<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Proposal</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 14px;
      color: #333;
      padding: 40px;
      line-height: 1.6;
    }
    h1 {
      font-size: 22px;
      margin-bottom: 10px;
      color: #1a202c;
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 6px;
    }
    .section {
      margin-bottom: 20px;
    }
    .label {
      font-weight: bold;
      color: #4a5568;
      margin-bottom: 4px;
    }
    .value {
      margin-bottom: 10px;
    }
    .footer {
      font-size: 12px;
      color: #718096;
      margin-top: 40px;
      text-align: center;
    }
  </style>
</head>
<body>
  <img src="{{ public_path('logo.png') }}" style="width:120px; margin-bottom:20px;">
  <h1>Proposal for {{ $client_name }}</h1>

  <div class="section">
    <div class="label">Project Title</div>
    <div class="value">{{ $project_title }}</div>
  </div>

  <div class="section">
    <div class="label">Scope</div>
    <div class="value">{{ $scope }}</div>
  </div>

  <div class="section">
    <div class="label">Timeline</div>
    <div class="value">{{ $timeline }}</div>
  </div>

  <div class="section">
    <div class="label">Pricing</div>
    <div class="value">{{ $pricing }}</div>
  </div>

  <div class="section">
    <div class="label">Deliverables</div>
    <div class="value">{{ $deliverables }}</div>
  </div>

  <div class="footer">
    Generated by Client Proposal Generator — {{ now()->format('F j, Y') }}
  </div>
</body>
</html>